# Generated by Django 3.1.4 on 2020-12-09 10:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('other', 'other'), ('red', 'red'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('sony', 'sony'), ('canon', 'canon'), ('nikon', 'nikon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('gaming', 'gaming'), ('code', 'code'), ('comdey', 'comdey'), ('film_making', 'film_making'), ('vlogs', 'vlogs'), ('mobile_review', 'mobile_review'), ('cooking', 'cooking')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large'), ('solo', 'solo')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
