# Generated by Django 3.1.4 on 2020-12-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0004_auto_20201210_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('red', 'red'), ('canon', 'canon'), ('fuji', 'fuji'), ('nikon', 'nikon'), ('panasonic', 'panasonic'), ('other', 'other'), ('sony', 'sony')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('comdey', 'comdey'), ('cooking', 'cooking'), ('gaming', 'gaming'), ('mobile_review', 'mobile_review'), ('code', 'code'), ('vlogs', 'vlogs'), ('film_making', 'film_making')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('small', 'small'), ('large', 'large'), ('solo', 'solo')], max_length=255),
        ),
    ]
