# Generated by Django 3.1.4 on 2020-12-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0007_auto_20201210_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('other', 'other'), ('red', 'red'), ('nikon', 'nikon'), ('panasonic', 'panasonic'), ('canon', 'canon'), ('sony', 'sony'), ('fuji', 'fuji')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('comdey', 'comdey'), ('gaming', 'gaming'), ('film_making', 'film_making'), ('mobile_review', 'mobile_review'), ('vlogs', 'vlogs'), ('code', 'code'), ('cooking', 'cooking')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('large', 'large'), ('small', 'small'), ('solo', 'solo')], max_length=255),
        ),
    ]
