# Generated by Django 3.1.4 on 2020-12-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0009_auto_20201211_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('panasonic', 'panasonic'), ('fuji', 'fuji'), ('nikon', 'nikon'), ('sony', 'sony'), ('other', 'other'), ('red', 'red'), ('canon', 'canon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('mobile_review', 'mobile_review'), ('comdey', 'comdey'), ('film_making', 'film_making'), ('code', 'code'), ('gaming', 'gaming'), ('cooking', 'cooking'), ('vlogs', 'vlogs')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('large', 'large'), ('small', 'small')], max_length=255),
        ),
    ]
