# Generated by Django 3.1.4 on 2020-12-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0002_auto_20201209_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'sony'), ('other', 'other'), ('canon', 'canon'), ('fuji', 'fuji'), ('panasonic', 'panasonic'), ('nikon', 'nikon'), ('red', 'red')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('mobile_review', 'mobile_review'), ('code', 'code'), ('comdey', 'comdey'), ('cooking', 'cooking'), ('vlogs', 'vlogs'), ('film_making', 'film_making'), ('gaming', 'gaming')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('large', 'large'), ('small', 'small'), ('solo', 'solo')], max_length=255),
        ),
    ]
