# Generated by Django 3.1.4 on 2020-12-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0005_auto_20201210_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('fuji', 'fuji'), ('other', 'other'), ('sony', 'sony'), ('nikon', 'nikon'), ('panasonic', 'panasonic'), ('red', 'red'), ('canon', 'canon')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('film_making', 'film_making'), ('cooking', 'cooking'), ('vlogs', 'vlogs'), ('comdey', 'comdey'), ('code', 'code'), ('gaming', 'gaming'), ('mobile_review', 'mobile_review')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('large', 'large'), ('solo', 'solo'), ('small', 'small')], max_length=255),
        ),
    ]
