# Generated by Django 3.0.5 on 2020-12-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0008_auto_20201210_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtuber',
            name='camera_type',
            field=models.CharField(choices=[('sony', 'sony'), ('nikon', 'nikon'), ('other', 'other'), ('canon', 'canon'), ('fuji', 'fuji'), ('red', 'red'), ('panasonic', 'panasonic')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='category',
            field=models.CharField(choices=[('vlogs', 'vlogs'), ('mobile_review', 'mobile_review'), ('comdey', 'comdey'), ('cooking', 'cooking'), ('code', 'code'), ('film_making', 'film_making'), ('gaming', 'gaming')], max_length=255),
        ),
        migrations.AlterField(
            model_name='youtuber',
            name='crew',
            field=models.CharField(choices=[('solo', 'solo'), ('small', 'small'), ('large', 'large')], max_length=255),
        ),
    ]
